#!/bin/bash

INSTALLER_DIR="$(dirname $(readlink -f $0))"
NEW_DIR="/opt/acpi_wakeup"

SCRIPT="acpi_wakeup.py"
SCRIPT_BIN_PATH="/usr/bin/acpi_wakeup"
INSTALLER="installer"
VENV="venv"
SERVICE="acpi_wakeup.service"
SERVICE_PATH="/etc/systemd/system/${SERVICE}"


if [[ "$1" == "install" ]] || [[ "$1" == "-i" ]]; then
    echo "Installing (requires root)..."
    sudo mkdir -p ${NEW_DIR}
    sudo chmod +x ${INSTALLER_DIR}/${SCRIPT}
    sudo cp -f ${INSTALLER_DIR}/${SCRIPT} ${NEW_DIR}/${SCRIPT}
    sudo cp -f ${INSTALLER_DIR}/${SCRIPT} ${SCRIPT_BIN_PATH}
    sudo cp -f ${INSTALLER_DIR}/${INSTALLER} ${NEW_DIR}/${INSTALLER}
    sudo cp -rf ${INSTALLER_DIR}/${VENV} ${NEW_DIR}/${VENV}
    sudo cp -f ${INSTALLER_DIR}/${SERVICE} ${SERVICE_PATH}
    sudo systemctl enable ${SERVICE}
    sudo systemctl start ${SERVICE}
    sleep 1s
    sudo systemctl status ${SERVICE}
elif [[ "$1" == "uninstall" ]] || [[ "$1" == "-u" ]]; then
    echo "Uninstalling (requires root)..."
    sudo systemctl disable ${SERVICE}
    sudo rm -f ${SERVICE_PATH}
    sudo rm -f ${SCRIPT_BIN_PATH}
    sudo rm -rf ${NEW_DIR}
else
    echo "Options:"
    echo "    -i install    Install script and systemd service"
    echo "    -u uninstall  Uninstall script and systemd service"
fi
